### ISSUE TITLE
The linear prob and coco detection code

### ISSUE THREAD

**Issue by cheliu-computation** [Sherrylone/Query_Contrastive#2]
Hi, Thnaks for your impressive word and detailed pre-training code.
Would you mind provide the downstream tasks code for further fair comparsion?

**Comment by Sherrylone** [comment]
Thanks for your attention to our work. We have added the code of downstream tasks.

**Comment by cheliu-computation** [comment]
> Thanks for your attention to our work. We have added the code of downstream tasks.

Thanks!
